export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const ADD_CONTACT = 'ADD_CONTACT';
export const ADD_LOCATION  = 'ADD_LOCATION';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';
export const REMOVE_CONTACT = 'REMOVE_CONTACT';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const REMOVE_ADDRESS = 'REMOVE_ADDRESS';
